### PR TITLE
typesecript-peer-dependency

### PR DESCRIPTION
**Pull request by SalvatorePreviti**
Fix for https://github.com/deamme/ts-transform-inferno/issues/8

### CODE REVIEW

**Comment by deamme** [comment]
I wonder if you could just delete typescript from `devDependencies`?

**Comment by SalvatorePreviti** [comment]
Mhhh I don't think so, because it is needed to build the package. TypeScript being a peerDependency will not be installed, so it should be both a devDependency and a peerDependency. Keeping it as a peerDependency does not cause any harm and will print a warning when somebody try to install this package without installing also typescript, that is indeed a good thing. DevDependencies will never be installed when this package is required in another package, that is also a good thing.

**Comment by SalvatorePreviti** [comment]
By the way, also the other ts-transformer you have (and again, very good job with that) suffers of the same issue, so they are bound to a specific version of TypeScript and can cause problems when mixed with other TS versions. ts-transform-css-modules-next , 
ts-transform-classcat (that I would like to use). Would you like a pull request on these packages too?

**Comment by deamme** [comment]
@SalvatorePreviti Ah, I see! Would be awesome if you could make a PR for the other packages too. Thank you!

**Pull request merged**
